name: tls-scan build & release

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    env:
      echo "TLSSCAN_VERSION=$(grep Version -m 1 $GITHUB_WORKSPACE/CHANGELOG | awk '{printf "%s", $2}')" >> $GITHUB_ENV
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup build dependencies
      if: matrix.os == 'ubuntu-18.04'
      run: sudo apt install -y autoconf automake libtool pkg-config gcc unzip
    - name: Setup MacOS build dependencies
      if: matrix.os == 'macos-latest'
      run: brew install autoconf automake libtool
    - name: build-x86-64	
      run: ./build-x86-64.sh
   
    - name: build-linux-package
      if: matrix.os == 'ubuntu-18.04'
      echo "TLSSCAN_OS=linux" >> $GITHUB_ENV
      run: rm $GITHUB_WORKSPACE/tls-scan
      run: mkdir -p $GITHUB_WORKSPACE/tls-scan/man/man1
      run: cp $GITHUB_WORKSPACE/build-root/bin/tls-scan $GITHUB_WORKSPACE/tls-scan/tls-scan
      run: cp $GITHUB_WORKSPACE/build-root/share/man/man1/tls-scan.1 $GITHUB_WORKSPACE/tls-scan/man/man1/tls-scan.1
      run: cp $GITHUB_WORKSPACE/build-root/etc/tls-scan/ca-bundle.crt $GITHUB_WORKSPACE/tls-scan/ca-bundle.crt
      run: tar -zcvf tls-scan-${{env.TLSSCAN_VERSION}}-${{env.TLSSCAN_OS}}-amd64.tar.gz ./tls-scan/

    - name: build-macos-packages
      if: matrix.os == 'macos-latest'
      echo "TLSSCAN_OS=darwin" >> $GITHUB_ENV  
      run: rm $GITHUB_WORKSPACE/tls-scan
      run: mkdir -p $GITHUB_WORKSPACE/tls-scan/man/man1
      run: cp $GITHUB_WORKSPACE/build-root/bin/tls-scan $GITHUB_WORKSPACE/tls-scan/tls-scan
      run: cp $GITHUB_WORKSPACE/build-root/share/man/man1/tls-scan.1 $GITHUB_WORKSPACE/tls-scan/man/man1/tls-scan.1
      run: cp $GITHUB_WORKSPACE/build-root/etc/tls-scan/ca-bundle.crt $GITHUB_WORKSPACE/tls-scan/ca-bundle.crt
      run: tar -zcvf tls-scan-${{env.TLSSCAN_VERSION}}-${{env.TLSSCAN_OS}}-amd64.tar.gz ./tls-scan/

    - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tls-scan-${{env.TLSSCAN_VERSION}}-${{env.TLSSCAN_OS}}-amd64.tar.gz
